### ISSUE TITLE
undefined method `authenticate=' for #<Faraday::ConnectionOptions:0x007fd840b03158> (NoMethodError)

### ISSUE THREAD

**Issue by codeundercoverdev** [DockYard/party_foul#129]
I have used party_foul countless times before and have never had this problem.

When I run `rails g party_foul:install` I get the following error:

```
/Users/kevin/.rvm/gems/ruby-2.3.0/gems/faraday-0.10.0/lib/faraday/options.rb:31:in `block in update': undefined method `authenticate=' for #<Faraday::ConnectionOptions:0x007fd840b03158> (NoMethodError)
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/faraday-0.10.0/lib/faraday/options.rb:20:in `each'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/faraday-0.10.0/lib/faraday/options.rb:20:in `update'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/faraday-0.10.0/lib/faraday/options.rb:52:in `merge'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:59:in `initialize'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/faraday-0.10.0/lib/faraday.rb:70:in `new'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/faraday-0.10.0/lib/faraday.rb:70:in `new'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/octokit-1.25.0/lib/octokit/connection.rb:25:in `connection'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/octokit-1.25.0/lib/octokit/request.rb:65:in `request'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/octokit-1.25.0/lib/octokit/request.rb:29:in `post'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/octokit-1.25.0/lib/octokit/client/authorizations.rb:55:in `create_authorization'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/party_foul-1.3.1/lib/generators/party_foul/install_generator.rb:18:in `create_initializer_file'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/generators.rb:180:in `invoke'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:60:in `generate'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
    from /Users/kevin/expo/expo_projects/expo-alv/bin/rails:9:in `<top (required)>'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/kevin/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
    from /Users/kevin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/kevin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

Any ideas?

**Comment by yogeshjain999** [comment]
@codeundercoverdev Try updating the version. I'm getting this issue for `1.3.1` but not for `1.5.5`.
